### PR TITLE
fix

### PR DESCRIPTION
**Pull request by robwormald**
this is the pattern i've been using - keeping all the app code in a folder seems to work a lot more sanely.

### CODE REVIEW

**Comment by frankwallis** [comment]
that does the trick, thanks!

**Comment by robwormald** [comment]
I do it this way so that the app/ directory is "virtual" - which is useful if I want to transpile TS to /temp, and then you can simply override that path from app -> src to app -> temp, and then the builder picks up the JS files.

**Comment by frankwallis** [comment]
I see, that could be useful for distribution I suppose.

**Comment by robwormald** [comment]
Totally pedantic, but I'm pretty much using 'main' as the file name for my entry point, which eliminates getting tangled up in app/app / "does the app refer to my pacakge or my file" etc:
- declare package called app
- its main file is app/main 
- System.import('app');

**Comment by frankwallis** [comment]
that makes sense

**Pull request merged**
